import {Store,Sfx,makeEnv} from './core.js';
import {NexusSync} from './nexus-sync.js';
import {isNativeGame,loadNativeGame} from './native-games/loader.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sync=new NexusSync(),store=new Store(sync);let sfx,Mechanics=null,mechanicsPromise=null,ambient=null,games=[],current=null,runner=null,mode='ai',difficulty='medium',championship=[],champIndex=0,matchId='';
const catalog=$('#catalogView'),gameView=$('#gameView'),grid=$('#gameGrid'),back=$('#backBtn');
const PUZZLE_IDS=new Set([15,28,30,37,42,49,53,55,58,61,64]);
const palettes=[['#ffb72b','#ff5f73'],['#45c7ff','#5865ff'],['#7ae33c','#2dbd95'],['#db63ff','#7c4dff'],['#ffcf37','#ff7a32'],['#55e0cf','#168bc7'],['#ff7297','#8d55ff'],['#8adb43','#ffc53d']];
function syncTheme(){const pref=store.data.theme||'system',dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function setCoins(){const c=$('#coinCount');if(c)c.textContent=store.coins();const a=$('#accountBtn');if(!a)return;if(store.mode==='account'){a.classList.add('signed');a.querySelector('.account-label').textContent=store.user?.displayName||'Compte';a.title=`Connecté : ${store.user?.email||''}`}else{a.classList.remove('signed');a.querySelector('.account-label').textContent='Invité';a.title='Mode invité — progression locale uniquement'}}
function art(g,compact=false){const[a,b]=palettes[(g.id-1)%palettes.length],shape=(g.id%6)+1;return `<div class="game-art shape-${shape} ${compact?'compact':''}" style="--a:${a};--b:${b}"><div class="art-glow"></div><div class="arena"><span class="prop p1"></span><span class="prop p2"></span><span class="prop p3"></span></div><div class="avatar red"><i></i><b></b><em></em></div><div class="avatar blue"><i></i><b></b><em></em></div><span class="mode-stamp">${g.mode==='solo'?'SOLO':'VS'}</span></div>`}
function card(g){const b=document.createElement('button');b.className='game-card premium-card';b.dataset.mode=g.mode;b.dataset.gameId=g.id;b.style.setProperty('--delay',`${(g.id%10)*28}ms`);b.innerHTML=`${art(g)}<div class="card-copy"><div class="card-kicker">${g.mode==='solo'?'1 PLAYER':'2 PLAYERS'}</div><h3>${g.name}</h3><p>${g.type}</p><div class="score-row"><span class="red-dot"></span><b>${store.stat(g.id).wins||0}</b><small>VS</small><b>${store.stat(g.id).losses||0}</b><span class="blue-dot"></span></div></div><span class="level-pill">LV ${store.stat(g.id).level||1}</span>`;b.onclick=()=>openGame(g.id);return b}
function render(filter=$('.segmented [data-filter].active')?.dataset.filter||'all'){grid.textContent='';const f=games.filter(g=>filter==='all'||g.mode===filter);f.forEach(g=>grid.append(card(g)));if(!f.length)grid.innerHTML='<div class="empty-state"><h2>Aucun jeu dans cette catégorie</h2></div>'}
async function loadMechanics(){if(Mechanics)return Mechanics;if(!mechanicsPromise)mechanicsPromise=import('./mechanics.js').then(m=>(Mechanics=m)).catch(e=>{mechanicsPromise=null;throw e});return mechanicsPromise}
function creator(id){return Mechanics?.[`createGame${String(id).padStart(2,'0')}`]}
function setGameLoading(on,msg='Chargement du jeu…'){let el=$('#gameLoading');if(!el){el=document.createElement('div');el.id='gameLoading';el.className='game-loading hidden';el.innerHTML='<div class="loader-orb"></div><strong></strong>';$('.canvas-wrap')?.append(el)}if(!el)return;el.querySelector('strong').textContent=msg;el.classList.toggle('hidden',!on)}
function updatePuzzleTools(){const bar=$('#puzzleTools');bar?.classList.toggle('hidden',!current||!PUZZLE_IDS.has(current.id))}
function finish(win,msg){if(win)sfx?.win?.();else sfx?.fail?.();$('#resultTitle').textContent=win?'Victoire !':'Manche terminée';$('#resultText').textContent=msg||'';$('#coinReward').classList.toggle('hidden',!win);$('#resultOverlay').classList.remove('hidden');store.result(current.id,!!win,matchId).then(()=>{setCoins();render();$('#syncStatus').textContent=store.mode==='account'?'Synchronisé avec Nexus':'Sauvegardé sur cet appareil'}).catch(()=>{$('#syncStatus').textContent='Synchronisation en attente'});if(championship.length&&win){champIndex++;$('#nextBtn').textContent=champIndex<championship.length?'Jeu suivant':'Terminer'}}
async function openGame(id){const g=games.find(x=>x.id===id);if(!g)return;current=g;catalog.classList.add('hidden');gameView.classList.remove('hidden');back.classList.remove('hidden');$('#gameTitle').textContent=g.name;$('#gameSubtitle').textContent=g.type;$('#gameIcon').innerHTML=art(g,true);$('#infoTitle').textContent=g.name;$('#infoType').textContent=g.type;$('#infoPrompt').textContent=g.prompt||g.type;const pvp=$('#modeSelector [data-mode="pvp"]'),ai=$('#modeSelector [data-mode="ai"]');if(g.mode==='solo'){mode='ai';pvp.classList.add('hidden');ai.textContent='Solo'}else{pvp.classList.remove('hidden');ai.textContent='Solo IA'}$$('#modeSelector button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#resultOverlay').classList.add('hidden');updatePuzzleTools();history.replaceState(null,'',`?game=${id}`);setGameLoading(true);try{await startCurrent()}catch(err){console.error(err);setGameLoading(true,'Ce jeu n’a pas pu charger. Réessaie.');$('#syncStatus').textContent='Erreur moteur isolée — catalogue toujours disponible'}}
async function startCurrent(){if(!current)return;setGameLoading(true);runner?.destroy?.();runner=null;$('#resultOverlay').classList.add('hidden');matchId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const tutorial=$('#tutorial');tutorial.textContent=current?.type||'Joue';tutorial.style.opacity=1;setTimeout(()=>tutorial.style.opacity=.05,2800);const canvas=$('#gameCanvas'),built=makeEnv(canvas,store,sfx,{mode,difficulty,level:store.stat(current.id).level||1},finish);if(isNativeGame(current.id)){const create=await loadNativeGame(current.id);built.destroy();runner=await create(built.env);setGameLoading(false);$('#syncStatus').textContent=`${games.length} jeux · moteur natif progressif`;return}await loadMechanics();const create=creator(current.id);if(!create){built.destroy();throw new Error(`Mécanique ${current.id} indisponible`)}runner=built;runner.setScene(create(built.env));setGameLoading(false)}
function closeGame(){runner?.destroy?.();runner=null;current=null;championship=[];catalog.classList.remove('hidden');gameView.classList.add('hidden');back.classList.add('hidden');history.replaceState(null,'',location.pathname)}
function startAmbient(){if(ambient||!window.AudioContext)return;try{const Ctx=window.AudioContext||window.webkitAudioContext,ctx=new Ctx(),master=ctx.createGain();master.gain.value=.018;master.connect(ctx.destination);const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=110;gain.gain.value=.18;osc.connect(gain).connect(master);osc.start();const lfo=ctx.createOscillator(),lg=ctx.createGain();lfo.frequency.value=.07;lg.gain.value=16;lfo.connect(lg).connect(osc.frequency);lfo.start();ambient={ctx,master,on:true}}catch{}}
function toggleAmbient(){startAmbient();if(!ambient)return false;ambient.on=!ambient.on;ambient.master.gain.setTargetAtTime(ambient.on?.018:0,ambient.ctx.currentTime,.08);return ambient.on}
function rewardDemo(kind){const o=$('#adRewardOverlay');if(!o)return;o.classList.remove('hidden');o.querySelector('strong').textContent=kind==='tube'?'Tube bonus':'Indice bonus';let n=3,c=o.querySelector('[data-count]');c.textContent=n;const t=setInterval(()=>{c.textContent=--n;if(n<=0){clearInterval(t);o.classList.add('hidden');$('#tutorial').textContent=kind==='tube'?'Tube bonus débloqué pour cette manche':'Indice débloqué : cherche à libérer une couleur complète';$('#tutorial').style.opacity=1}},1000)}
back.onclick=closeGame;$('#replayBtn').onclick=()=>startCurrent();$('#restartBtn').onclick=()=>runner?.restart?.()||startCurrent();$('#nextBtn').onclick=()=>{if(championship.length&&champIndex<championship.length)return openGame(championship[champIndex]);openGame(games[Math.floor(Math.random()*games.length)].id)};$('#randomBtn').onclick=()=>games.length&&openGame(games[Math.floor(Math.random()*games.length)].id);$('#champBtn').onclick=()=>{if(!games.length)return;championship=[...games].sort(()=>Math.random()-.5).slice(0,5).map(g=>g.id);champIndex=0;openGame(championship[0])};
$$('.segmented [data-filter]').forEach(b=>b.onclick=()=>{$$('.segmented [data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});$$('#modeSelector button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('#modeSelector button').forEach(x=>x.classList.toggle('active',x===b));startCurrent()});$('#difficulty').onchange=e=>{difficulty=e.target.value;startCurrent()};$('#soundBtn').onclick=()=>{const gameSound=sfx?.toggle?.()??true,music=toggleAmbient();$('#soundBtn').textContent=`Son ${gameSound?'ON':'OFF'} · Musique ${music?'ON':'OFF'}`};$('#themeBtn').onclick=()=>{const p=store.data.theme||'system';store.setTheme(p==='system'?'dark':p==='dark'?'light':'system');syncTheme()};$('#infoBtn').onclick=()=>$('#infoDialog').showModal();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',syncTheme);document.addEventListener('pointerdown',startAmbient,{once:true});
$('#hintReward')?.addEventListener('click',()=>{const h=runner?.hint?.();if(h){$('#tutorial').textContent=`Indice : ${h.from+1} → ${h.to+1}`;$('#tutorial').style.opacity=1}else rewardDemo('hint')});$('#tubeReward')?.addEventListener('click',()=>{if(!runner?.addTube?.())rewardDemo('tube')});$('#undoPuzzle')?.addEventListener('click',()=>{if(!runner?.undo?.()){$('#tutorial').textContent='Aucun coup à annuler';$('#tutorial').style.opacity=1}});
const authDialog=$('#authDialog');function authMessage(msg,type=''){const el=$('#authMessage');el.textContent=msg;el.dataset.type=type}function accountOpen(){authMessage('');$('#signedOutPanel').classList.toggle('hidden',store.mode==='account');$('#signedInPanel').classList.toggle('hidden',store.mode!=='account');if(store.mode==='account'){$('#accountName').textContent=store.user?.displayName||'Nexus';$('#accountEmail').textContent=store.user?.email||'';$('#accountCloudCoins').textContent=store.coins();$('#accountCloudLevel').textContent=Math.max(1,...Object.values(store.data.stats||{}).map(s=>s.level||1))}authDialog.showModal()}
$('#accountBtn').onclick=accountOpen;$('#closeAuth').onclick=()=>authDialog.close();$('#signInForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||'');if(!window.NEXUS_CONFIG?.url){authMessage('Nexus Cloud est en cours d’activation. Tu peux jouer en invité sans mélanger ta progression.','warn');return}authMessage('Connexion…');try{await sync.signIn(email,password);authMessage('Connecté. La progression cloud a été chargée.','ok');$('#signedOutPanel').classList.add('hidden');$('#signedInPanel').classList.remove('hidden');setCoins();render();setTimeout(()=>authDialog.close(),500)}catch(err){authMessage(err.message||'Connexion impossible','error')}};$('#showSignUp').onclick=()=>{$('#signupFields').classList.toggle('hidden');$('#signUpBtn').classList.toggle('hidden')};$('#signUpBtn').onclick=async()=>{const fd=new FormData($('#signInForm')),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||''),name=String(fd.get('displayName')||'').trim();if(!window.NEXUS_CONFIG?.url){authMessage('Nexus Cloud est en cours d’activation.','warn');return}try{const r=await sync.signUp(email,password,name);authMessage(r.needsEmailConfirmation?'Compte créé. Vérifie ton e-mail avant de te connecter.':'Compte créé et connecté.','ok');setCoins();render()}catch(err){authMessage(err.message||'Création impossible','error')}};$('#signOutBtn').onclick=async()=>{await sync.signOut();authDialog.close();setCoins();render();syncTheme()};store.onChange(()=>{setCoins();syncTheme()});window.addEventListener('online',()=>sync.flushPending().catch(()=>{}));
(async()=>{try{games=await fetch('./games.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Catalogue introuvable');return r.json()});render();$('#syncStatus').textContent=`${games.length} jeux chargés · moteur progressif`;try{await store.init();sfx=new Sfx(store);syncTheme();setCoins();$('#soundBtn').textContent=`Son ${sfx.on?'ON':'OFF'} · Musique OFF`}catch(err){console.warn('Progression locale indisponible',err);syncTheme()}const id=Number(new URLSearchParams(location.search).get('game'));if(id>=1&&id<=64)openGame(id)}catch(err){console.error(err);grid.innerHTML=`<div class="empty-state"><h2>Impossible de charger les jeux</h2><p>${err.message||'Erreur inconnue'}</p><button class="primary" onclick="location.reload()">Réessayer</button></div>`}})();