import {Store,Sfx,makeEnv} from './core.js';
import {NexusSync} from './nexus-sync.js';
import {loadMechanics} from './mechanics-loader.js';
let Mechanics={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sync=new NexusSync();const store=new Store(sync);let sfx;
let games=[],current=null,runner=null,mode='ai',difficulty='medium',championship=[],champIndex=0,matchId='';
const catalog=$('#catalogView'),gameView=$('#gameView'),grid=$('#gameGrid'),back=$('#backBtn');
const creator=id=>Mechanics[`createGame${String(id).padStart(2,'0')}`];
function syncTheme(){const pref=store.data.theme||'system',dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function setCoins(){ $('#coinCount').textContent=store.coins();const account=$('#accountBtn');if(store.mode==='account'){account.classList.add('signed');account.querySelector('.account-label').textContent=store.user?.displayName||'Compte';account.title=`Connecté : ${store.user?.email||''}`}else{account.classList.remove('signed');account.querySelector('.account-label').textContent='Invité';account.title='Mode invité — progression locale uniquement'} }
function badge(g){const n=String(g.id).padStart(2,'0');return `<div class="game-badge game-badge-${(g.id%8)+1}" aria-hidden="true"><span>${n}</span><b>${g.mode==='solo'?'1P':'2P'}</b></div>`}
function card(g){const b=document.createElement('button');b.className='game-card';b.dataset.mode=g.mode;b.innerHTML=`${badge(g)}<div><h3>${g.name}</h3><p>${g.mode==='solo'?'Solo • niveaux':'2 joueurs • IA'}</p></div><span class="level-pill">Niv. ${store.stat(g.id).level||1}</span>`;b.onclick=()=>openGame(g.id);return b}
function render(filter=$('.segmented [data-filter].active')?.dataset.filter||'all'){grid.textContent='';games.filter(g=>filter==='all'||g.mode===filter).forEach(g=>grid.append(card(g)))}
async function openGame(id){const g=games.find(x=>x.id===id);if(!g)return;current=g;catalog.classList.add('hidden');gameView.classList.remove('hidden');back.classList.remove('hidden');$('#gameTitle').textContent=g.name;$('#gameSubtitle').textContent=g.type;$('#gameIcon').innerHTML=badge(g);$('#infoTitle').textContent=g.name;$('#infoType').textContent=g.type;$('#infoPrompt').textContent=g.prompt;const pvpBtn=$('#modeSelector [data-mode="pvp"]'),aiBtn=$('#modeSelector [data-mode="ai"]');if(g.mode==='solo'){mode='ai';pvpBtn.classList.add('hidden');aiBtn.textContent='Solo'}else{pvpBtn.classList.remove('hidden');aiBtn.textContent='Solo IA'}$$('#modeSelector button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#resultOverlay').classList.add('hidden');startCurrent();history.replaceState(null,'',`?game=${id}`)}
function startCurrent(){runner?.destroy?.();$('#resultOverlay').classList.add('hidden');matchId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const tutorial=$('#tutorial');tutorial.textContent=current?.type||'Joue';tutorial.style.opacity=1;setTimeout(()=>tutorial.style.opacity=.05,2800);const built=makeEnv($('#gameCanvas'),store,sfx,{mode,difficulty},(win,msg)=>{if(win)sfx.win();else sfx.fail();$('#resultTitle').textContent=win?'Victoire !':'Manche terminée';$('#resultText').textContent=msg||'';$('#coinReward').classList.toggle('hidden',!win);$('#resultOverlay').classList.remove('hidden');store.result(current.id,!!win,matchId).then(()=>{setCoins();render();$('#syncStatus').textContent=store.mode==='account'?'Synchronisé avec Nexus':'Sauvegardé sur cet appareil'}).catch(()=>{$('#syncStatus').textContent='Synchronisation en attente'});if(championship.length&&win){champIndex++;$('#nextBtn').textContent=champIndex<championship.length?'Jeu suivant':'Terminer'}});runner=built;const create=creator(current.id);if(!create)throw new Error(`Mécanique manquante pour le jeu ${current.id}`);runner.setScene(create(built.env))}
function closeGame(){runner?.destroy?.();runner=null;current=null;championship=[];catalog.classList.remove('hidden');gameView.classList.add('hidden');back.classList.add('hidden');history.replaceState(null,'',location.pathname)}
back.onclick=closeGame;$('#replayBtn').onclick=startCurrent;$('#restartBtn').onclick=startCurrent;$('#nextBtn').onclick=()=>{$('#resultOverlay').classList.add('hidden');if(championship.length&&champIndex<championship.length){openGame(championship[champIndex]);return}openGame(games[Math.floor(Math.random()*games.length)].id)};$('#randomBtn').onclick=()=>openGame(games[Math.floor(Math.random()*games.length)].id);$('#champBtn').onclick=()=>{championship=[...games].sort(()=>Math.random()-.5).slice(0,5).map(g=>g.id);champIndex=0;openGame(championship[0])};
$$('.segmented [data-filter]').forEach(b=>b.onclick=()=>{$$('.segmented [data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});$$('#modeSelector button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('#modeSelector button').forEach(x=>x.classList.toggle('active',x===b));startCurrent()});$('#difficulty').onchange=e=>{difficulty=e.target.value;startCurrent()};$('#soundBtn').onclick=()=>{$('#soundBtn').textContent=`Son: ${sfx.toggle()?'ON':'OFF'}`};$('#themeBtn').onclick=()=>{const p=store.data.theme||'system';store.setTheme(p==='system'?'dark':p==='dark'?'light':'system');syncTheme()};$('#infoBtn').onclick=()=>$('#infoDialog').showModal();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',syncTheme);

const authDialog=$('#authDialog');
function authMessage(msg,type=''){const el=$('#authMessage');el.textContent=msg;el.dataset.type=type}
function accountOpen(){authMessage('');$('#signedOutPanel').classList.toggle('hidden',store.mode==='account');$('#signedInPanel').classList.toggle('hidden',store.mode!=='account');if(store.mode==='account'){$('#accountName').textContent=store.user?.displayName||'Nexus';$('#accountEmail').textContent=store.user?.email||'';$('#accountCloudCoins').textContent=store.coins();$('#accountCloudLevel').textContent=Math.max(1,...Object.values(store.data.stats||{}).map(s=>s.level||1))}authDialog.showModal()}
$('#accountBtn').onclick=accountOpen;$('#closeAuth').onclick=()=>authDialog.close();
$('#signInForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||'');if(!window.NEXUS_CONFIG?.url){authMessage('Nexus Cloud est en cours d’activation. Tu peux jouer en invité sans mélanger ta progression.','warn');return}authMessage('Connexion…');try{await sync.signIn(email,password);authMessage('Connecté. La progression cloud a été chargée.','ok');$('#signedOutPanel').classList.add('hidden');$('#signedInPanel').classList.remove('hidden');setCoins();render();setTimeout(()=>authDialog.close(),500)}catch(err){authMessage(err.message||'Connexion impossible','error')}};
$('#showSignUp').onclick=()=>{$('#signupFields').classList.toggle('hidden');$('#signUpBtn').classList.toggle('hidden')};
$('#signUpBtn').onclick=async()=>{const form=$('#signInForm'),fd=new FormData(form),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||''),name=String(fd.get('displayName')||'').trim();if(!window.NEXUS_CONFIG?.url){authMessage('Nexus Cloud est en cours d’activation.','warn');return}try{const r=await sync.signUp(email,password,name);if(r.needsEmailConfirmation)authMessage('Compte créé. Vérifie ton e-mail avant de te connecter.','ok');else{authMessage('Compte créé et connecté.','ok');setCoins();render()}}catch(err){authMessage(err.message||'Création impossible','error')}};
$('#signOutBtn').onclick=async()=>{await sync.signOut();authDialog.close();setCoins();render();syncTheme()};
store.onChange(()=>{setCoins();syncTheme()});window.addEventListener('online',()=>sync.flushPending().catch(()=>{}));
(async()=>{await store.init();sfx=new Sfx(store);syncTheme();setCoins();$('#soundBtn').textContent=`Son: ${sfx.on?'ON':'OFF'}`;Mechanics=await loadMechanics();games=await fetch('./games.json',{cache:'no-store'}).then(r=>r.json());render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const id=Number(new URLSearchParams(location.search).get('game'));if(id>=1&&id<=64)openGame(id)})();