const profiles={1:['race','Sprint Rivals'],2:['collect','Dungeon Duel'],3:['collect','Hungry Ghost Feast'],4:['collect','Fish Frenzy Cats'],5:['tap','Mole Smash Duo'],6:['timing','Top Clash'],7:['duel','Air Hockey Duel'],8:['avoid','Sky Hoppers'],9:['collect','Hungry River Hippo'],10:['draw','Doodle Duel'],11:['tap','Sun Zap Prank'],12:['race','Star Chase Ludo'],13:['duel','Bumper Cars Arena'],14:['race','Marble Melon Race'],15:['puzzle','Puzzle Rush'],16:['avoid','Dodgeball Duel'],17:['timing','Rope Pull Rivals'],18:['timing','Ice Curling Duel'],19:['avoid','Grim Chase'],20:['duel','Soccer Clash Mini'],21:['race','Drift Duel Circuit'],22:['timing','Table Cloth Pull'],23:['timing','Blade Spin Duel'],24:['tap','Zombie Shootout Duo'],25:['race','Cake Bite Race'],26:['tap','Bow Clash Duel'],27:['duel','Shadow Fighters Clash'],29:['timing','Arms Clash Duel'],35:['duel','Sumo Ring Clash'],36:['timing','Pirate Barrel Clash'],37:['puzzle','Minefield Duel'],38:['collect','Egg Heist Duel'],39:['avoid','Cop & Robber Chase'],40:['race','Brush Speed Race'],41:['duel','Goal Clash Reverse'],43:['avoid','Rocket Rivalry'],44:['collect','Crewmate Clash'],45:['tap','Cannon Duel Shield'],46:['avoid','Avocado Dodge Duel'],47:['duel','Pool Table Clash'],48:['duel','Paddle Clash Duo'],57:['tap','Ninja Pup Strike'],59:['tap','Castle Siege Defense'],60:['avoid','Earth Shield Defender'],61:['puzzle','Dorm of Whispers'],62:['duel','Tank Clash Arena'],63:['race','Pedal Rush Race']};
const themes={race:['#07152d','#4fd1ff'],collect:['#071f19','#63e6a5'],tap:['#25101d','#ff6b8a'],timing:['#1d1428','#c084fc'],duel:['#0b1728','#60a5fa'],avoid:['#08211e','#5eead4'],draw:['#21132d','#e879f9'],puzzle:['#11152b','#818cf8']};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const seeded=id=>{let x=(id*2654435761)>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296)};
export async function createConfiguredNativeGame(env,id){
 const [mode,title]=profiles[id]||['tap',`Nexus Game ${id}`],{canvas,ctx,sfx,options={}}=env,rng=seeded(id+(options.level||1)*97);
 let raf=0,running=true,paused=false,score=0,lives=3,progress=0,combo=0,bestCombo=0,objects=[],particles=[],started=performance.now(),last=0,lastHit=0,pointer={x:0,y:0,down:false,path:[]};
 const difficulty=clamp((options.level||1)+Math.floor(id/16),1,8),goal=mode==='timing'?6+difficulty:mode==='race'||mode==='duel'||mode==='draw'?100:10+difficulty;
 const spawnObjects=r=>{const count=mode==='tap'||mode==='collect'||mode==='puzzle'?goal:8+difficulty;objects=Array.from({length:count},(_,i)=>({x:45+rng()*Math.max(120,r.width-90),y:90+rng()*Math.max(120,r.height-150),r:15+rng()*10,active:true,vx:-(.7+rng()*.8+difficulty*.05),vy:(rng()-.5)*.35,phase:rng()*6.28}))};
 const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(globalThis.devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width*d)),h=Math.max(1,Math.floor(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ctx.setTransform(d,0,0,d,0,0);if(!objects.length)spawnObjects(r)}return r};
 const burst=(x,y,c)=>{for(let i=0;i<10;i++)particles.push({x,y,vx:(rng()-.5)*4,vy:(rng()-.5)*4,life:1,c})};
 const reset=()=>{running=true;paused=false;score=0;lives=3;progress=0;combo=0;bestCombo=0;started=performance.now();last=0;lastHit=0;pointer={x:0,y:0,down:false,path:[]};objects=[];particles=[];resize()};
 const win=m=>{if(!running)return;running=false;sfx?.score?.();env.end?.(true,m||'Challenge cleared')};
 const lose=m=>{if(!running)return;running=false;combo=0;sfx?.tap?.();env.end?.(false,m||'Round ended')};
 const award=(amount=1)=>{const now=performance.now();combo=now-lastHit<900?combo+1:1;lastHit=now;bestCombo=Math.max(bestCombo,combo);score+=amount+Math.floor(combo/4);sfx?.score?.()};
 const hit=e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;pointer.down=true;if(!running||paused)return;
  if(mode==='tap'||mode==='collect'||mode==='puzzle'){const o=objects.find(v=>v.active&&Math.hypot(pointer.x-v.x,pointer.y-v.y)<v.r+20);if(o){o.active=false;progress++;award();burst(o.x,o.y,(themes[mode]||themes.tap)[1]);if(progress>=goal)win(`${title} terminé`)}else if(mode==='tap'){combo=0;if(--lives<=0)lose('Plus d’essais')}}
  else if(mode==='timing'){const target=.5+.34*Math.sin(performance.now()/(440-difficulty*18)),ratio=clamp(pointer.x/Math.max(1,r.width),0,1),delta=Math.abs(ratio-target);if(delta<.11){progress++;award(delta<.045?2:1);burst(pointer.x,r.height*.5,themes.timing[1]);if(progress>=goal)win('Timing parfait')}else{combo=0;if(--lives<=0)lose('Timing manqué')}}
  else if(mode==='race'){const gain=8+difficulty*.7+Math.min(combo,6);progress=clamp(progress+gain,0,100);award(2);if(progress>=100)win('Arrivée franchie')}
  else if(mode==='duel'){const center=r.width/2,accuracy=1-Math.min(1,Math.abs(pointer.x-center)/(r.width*.5));progress=clamp(progress+7+accuracy*6,0,100);award(accuracy>.72?2:1);if(progress>=100)win('Duel remporté')}
  else if(mode==='draw'){pointer.path=[{x:pointer.x,y:pointer.y}];progress=0}
 };
 const move=e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;if(!running||paused)return;if(mode==='avoid'){progress=clamp(progress+.16,0,100)}else if(mode==='draw'&&pointer.down){const p=pointer.path.at(-1);if(!p||Math.hypot(pointer.x-p.x,pointer.y-p.y)>5){pointer.path.push({x:pointer.x,y:pointer.y});progress=clamp(progress+.9,0,100);if(progress>=100){award(3);win('Dessin complété')}}}};
 const up=()=>{pointer.down=false;if(mode==='draw'&&running&&progress<100)combo=0};
 const update=(t,r)=>{if(!running||paused)return;const dt=Math.min(32,last?t-last:16);last=t;if(mode==='avoid'){for(const o of objects){o.x+=o.vx*(dt/16);o.y+=o.vy*(dt/16);if(o.x<-30){o.x=r.width+30;o.y=85+rng()*Math.max(90,r.height-145);score++}if(pointer.x&&Math.hypot(pointer.x-o.x,pointer.y-o.y)<o.r+15){lives--;combo=0;o.x=r.width+40;burst(pointer.x,pointer.y,'#fff');if(lives<=0)lose('Collision')}}if(t-started>18000+difficulty*1100)win('Zone traversée')}else if(mode==='race'&&t-started>32000-difficulty*900)lose('Temps écoulé');
  for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vx*=.96;p.vy*=.96;p.life-=.035}particles=particles.filter(p=>p.life>0)};
 const drawScene=(t,r)=>{const c=themes[mode]||themes.tap,g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,c[0]);g.addColorStop(1,'#050914');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);
  ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='800 21px system-ui';ctx.fillText(title.toUpperCase(),r.width/2,31);ctx.font='600 12px system-ui';ctx.fillStyle='#c8d1ea';ctx.fillText(`Score ${score}   Combo x${combo}   Vies ${lives}`,r.width/2,53);
  ctx.fillStyle='rgba(255,255,255,.10)';ctx.fillRect(r.width*.1,67,r.width*.8,6);ctx.fillStyle=c[1];ctx.fillRect(r.width*.1,67,r.width*.8*(progress/goal),6);
  if(mode==='timing'){const target=.5+.34*Math.sin(t/(440-difficulty*18));ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(r.width*.12,r.height*.48,r.width*.76,30);ctx.fillStyle=c[1];ctx.fillRect(r.width*target-9,r.height*.48-5,18,40)}
  else if(mode==='race'){for(let i=0;i<6;i++){ctx.strokeStyle='rgba(255,255,255,.08)';ctx.beginPath();ctx.moveTo(0,r.height*.34+i*42);ctx.lineTo(r.width,r.height*.34+i*42);ctx.stroke()}const x=r.width*.1+r.width*.8*(progress/100);ctx.fillStyle=c[1];ctx.fillRect(x-12,r.height*.55-18,24,36)}
  else if(mode==='duel'){ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(r.width*.1,r.height*.52,r.width*.8,24);ctx.fillStyle=c[1];ctx.fillRect(r.width*.1,r.height*.52,r.width*.8*(progress/100),24);ctx.strokeStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.moveTo(r.width/2,r.height*.38);ctx.lineTo(r.width/2,r.height*.72);ctx.stroke()}
  else if(mode==='draw'){if(pointer.path.length>1){ctx.strokeStyle=c[1];ctx.lineWidth=7;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(pointer.path[0].x,pointer.path[0].y);for(const p of pointer.path.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke()}}
  else{for(const o of objects){if(!o.active)continue;const pulse=1+Math.sin(t/280+o.phase)*.07;ctx.beginPath();ctx.arc(o.x,o.y,o.r*pulse,0,Math.PI*2);ctx.fillStyle=c[1];ctx.fill();ctx.strokeStyle='rgba(255,255,255,.45)';ctx.lineWidth=2;ctx.stroke()}if(mode==='avoid'){ctx.beginPath();ctx.arc(pointer.x||r.width*.18,pointer.y||r.height*.55,16,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}}
  for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;if(paused){ctx.fillStyle='rgba(3,7,18,.72)';ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle='#fff';ctx.font='800 26px system-ui';ctx.fillText('PAUSE',r.width/2,r.height/2)}};
 const frame=t=>{const r=resize();update(t,r);drawScene(t,r);raf=requestAnimationFrame(frame)};
 reset();canvas.addEventListener('pointerdown',hit);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);raf=requestAnimationFrame(frame);
 return{restart:reset,pause(v=true){paused=!!v},resume(){paused=false;last=performance.now()},hint(){if(mode==='puzzle')return objects.findIndex(o=>o.active);if(mode==='timing')return'Tap near the moving marker';if(mode==='race')return'Build a steady tap rhythm';return null},getState:()=>({id,mode,title,score,progress,lives,combo,bestCombo,running,paused,difficulty}),destroy(){running=false;cancelAnimationFrame(raf);canvas.removeEventListener('pointerdown',hit);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up)}}
}
