const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const page=document.body.dataset.page||'home';let apps=[];let deferredPrompt=null;
const ua=navigator.userAgent||'';const isAndroid=/Android/i.test(ua);const isIOS=/iPhone|iPad|iPod/i.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const saved=new Set(JSON.parse(localStorage.getItem('nexus.saved')||'[]'));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>n.split(/\s|-/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const href=a=>`./app.html?id=${encodeURIComponent(a.id)}`;
function icon(a,large=false){if(a.icon)return`<img class="app-icon image-icon${large?' app-icon-large':''}" src="${esc(a.icon)}" alt="${esc(a.name)}">`;return`<div class="app-icon${large?' app-icon-large':''}" style="--c1:${a.colors?.[0]||'#253858'};--c2:${a.colors?.[1]||'#5b8cff'}">${esc(initials(a.name))}</div>`}
function platform(a){if(isAndroid&&a.android)return'Android';if(isIOS&&a.ios)return'iPhone / iPad';if(a.web)return'Web';if(a.android)return'Android';return'Bientôt'}
function action(a){if(isAndroid&&a.android)return['Installer',a.android];if(isIOS&&a.ios)return['Installer',a.ios];if(a.web)return['Ouvrir',a.web];if(a.android)return['Télécharger',a.android];return['Bientôt',null]}
function ratingData(id){const rows=JSON.parse(localStorage.getItem(`nexus.reviews.${id}`)||'[]');if(!rows.length)return{avg:null,count:0,rows};const avg=rows.reduce((s,r)=>s+Number(r.rating||0),0)/rows.length;return{avg,count:rows.length,rows}}
function card(a){const [label,url]=action(a),r=ratingData(a.id);return`<article class="app-row"><a class="app-link" href="${href(a)}">${icon(a)}<div class="app-copy"><h3>${esc(a.name)}</h3><div class="meta">${r.avg?r.avg.toFixed(1)+' ★ · ':''}${esc(a.category)} · ${esc(a.version||'')}</div><p>${esc(a.description||'')}</p></div></a><button class="pill-action${url?' ready':''}" data-app-action="${esc(a.id)}" ${url?'':'disabled'}>${label}</button></article>`}
function tile(a){const r=ratingData(a.id);return`<a class="app-tile" href="${href(a)}">${icon(a)}<h3>${esc(a.name)}</h3><span>${r.avg?r.avg.toFixed(1)+' ★ · ':''}${esc(a.category)}</span></a>`}
function saveState(){localStorage.setItem('nexus.saved',JSON.stringify([...saved]))}
function storeApp(){return apps.find(x=>x.id==='nexus-store')}
function openUrl(url){if(!url)return;if(url.startsWith('http'))window.open(url,'_blank','noopener');else location.href=url}
function install(a){const [,url]=action(a);if(!url)return;const store=storeApp();if(isAndroid&&a.id!=='nexus-store'&&a.android&&store?.android){const addStore=confirm('Ajouter aussi Nexus Store ?');if(addStore)window.open(store.android,'_blank','noopener');location.href=url;return}openUrl(url)}
function prioritized(){return[...apps].sort((a,b)=>(a.id==='nexus-store'?-1:b.id==='nexus-store'?1:0))}
function renderHome(){const list=prioritized(),f=$('#featuredApps'),p=$('#popularApps');if(f)f.innerHTML=list.slice(0,8).map(tile).join('');if(p)p.innerHTML=list.slice(0,10).map(card).join('')}
function renderSearch(){const input=$('#searchInput'),out=$('#searchResults');if(!input||!out)return;const params=new URLSearchParams(location.search);input.value=params.get('q')||'';let filter='all';const go=()=>{const q=input.value.trim().toLowerCase();const rows=prioritized().filter(a=>(filter==='all'||a.kind===filter||(filter==='web'&&a.web))&&(!q||`${a.name} ${a.category} ${a.description}`.toLowerCase().includes(q)));out.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty-state compact"><div class="empty-icon">⌕</div><h2>Aucun résultat</h2></div>'};input.addEventListener('input',go);$$('#searchChips .chip').forEach(b=>b.addEventListener('click',()=>{$$('#searchChips .chip').forEach(x=>x.classList.toggle('active',x===b));filter=b.dataset.filter;go()}));go()}
function renderCategories(){const grid=$('#categoryGrid'),out=$('#categoryApps');if(!grid||!out)return;const cats=[...new Set(apps.map(a=>a.category).filter(Boolean))];grid.innerHTML=cats.map((c,i)=>`<button class="category-card" data-category="${esc(c)}"><span>${['▦','◆','◉','✦','⌘','▣'][i%6]}</span><b>${esc(c)}</b></button>`).join('');const draw=c=>{out.innerHTML=prioritized().filter(a=>!c||a.category===c).map(card).join('')};grid.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;$$('.category-card').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.category)});draw()}
function renderLibrary(){const out=$('#libraryApps'),empty=$('#libraryEmpty');if(!out)return;const rows=prioritized().filter(a=>saved.has(a.id));out.innerHTML=rows.map(card).join('');if(empty)empty.hidden=rows.length>0}
function screenshotMarkup(a){const shots=Array.isArray(a.screenshots)?a.screenshots:[];if(!shots.length)return'<div class="preview-empty">Aperçus bientôt</div>';return`<div class="screenshots">${shots.map((s,i)=>`<img src="${esc(s)}" alt="${esc(a.name)} capture ${i+1}">`).join('')}</div>`}
function renderReviews(a){const box=$('#reviewsBlock');if(!box)return;const r=ratingData(a.id);box.innerHTML=`<div class="rating-summary"><div class="rating-big">${r.avg?r.avg.toFixed(1):'—'}</div><div><div class="stars">${r.avg?'★'.repeat(Math.round(r.avg)):'☆☆☆☆☆'}</div><small>${r.count?r.count+' avis':'Aucun avis'}</small></div></div><form id="reviewForm" class="review-form"><select id="reviewRating" aria-label="Note"><option value="5">5 ★</option><option value="4">4 ★</option><option value="3">3 ★</option><option value="2">2 ★</option><option value="1">1 ★</option></select><input id="reviewText" maxlength="280" placeholder="Votre avis"><button class="primary" type="submit">Publier</button></form><div class="review-list">${r.rows.slice().reverse().map(x=>`<article class="review"><b>${esc(x.rating)} ★</b><p>${esc(x.text||'')}</p><small>${esc(x.date||'')}</small></article>`).join('')}</div>`;$('#reviewForm').addEventListener('submit',e=>{e.preventDefault();const rows=r.rows;rows.push({rating:Number($('#reviewRating').value),text:$('#reviewText').value.trim(),date:new Date().toLocaleDateString()});localStorage.setItem(`nexus.reviews.${a.id}`,JSON.stringify(rows));renderReviews(a)})}
function renderDetail(){const id=new URLSearchParams(location.search).get('id');const a=apps.find(x=>x.id===id);const root=$('#appDetail');if(!root)return;if(!a){root.innerHTML='<div class="empty-state"><h1>Application introuvable</h1><a class="primary" href="./">Retour</a></div>';return}document.title=`${a.name} · Nexus Store`;const [label,url]=action(a),r=ratingData(a.id);const size=a.size||'—',compat=a.compatibility||(a.android?'Android 5.0+':a.web?'Navigateur moderne':'—'),updated=a.updated||'—',permissions=Array.isArray(a.permissions)?a.permissions:[];root.innerHTML=`<section class="detail-hero">${icon(a,true)}<div class="detail-title"><div class="eyebrow">${esc(a.category)}</div><h1>${esc(a.name)}</h1><p>${esc(a.developer||'Nexus Tech')}</p><div class="detail-actions"><button class="primary" id="detailAction" ${url?'':'disabled'}>${label}</button><button class="save-btn${saved.has(a.id)?' saved':''}" id="saveApp">${saved.has(a.id)?'✓ Enregistrée':'♡ Enregistrer'}</button></div></div></section><section class="stats"><div><b>${r.avg?r.avg.toFixed(1)+' ★':'Nouveau'}</b><span>${r.count?r.count+' avis':'Notes'}</span></div><div><b>${esc(size)}</b><span>Taille</span></div><div><b>${esc(platform(a))}</b><span>Plateforme</span></div><div><b>${esc(a.version||'—')}</b><span>Version</span></div></section><section class="store-section"><h2>Captures d’écran</h2>${screenshotMarkup(a)}</section><section class="detail-grid"><section class="store-section"><h2>À propos</h2><p>${esc(a.description||'')}</p>${a.changelog?`<h3>Nouveautés</h3><p>${esc(a.changelog)}</p>`:''}</section><section class="info-panel"><div><span>Mis à jour</span><b>${esc(updated)}</b></div><div><span>Compatibilité</span><b>${esc(compat)}</b></div><div><span>Développeur</span><b>${esc(a.developer||'Nexus Tech')}</b></div><div><span>Catégorie</span><b>${esc(a.category)}</b></div></section></section><section class="store-section"><h2>Confidentialité et permissions</h2>${permissions.length?`<div class="permission-list">${permissions.map(p=>`<span>${esc(p)}</span>`).join('')}</div>`:'<p>Aucune permission supplémentaire déclarée.</p>'}</section><section class="store-section"><h2>Notes et avis</h2><div id="reviewsBlock"></div></section>`;$('#detailAction')?.addEventListener('click',()=>install(a));$('#saveApp')?.addEventListener('click',()=>{saved.has(a.id)?saved.delete(a.id):saved.add(a.id);saveState();renderDetail()});renderReviews(a);const related=$('#relatedApps');if(related)related.innerHTML=prioritized().filter(x=>x.id!==a.id&&(x.category===a.category||x.kind===a.kind)).slice(0,7).map(tile).join('')}
function effectiveTheme(){const mode=localStorage.getItem('nexus.theme')||'system';if(mode==='system')return matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';return mode}
function applyTheme(){document.documentElement.dataset.theme=effectiveTheme()}
function renderSettings(){const theme=$('#themeMode'),notif=$('#notifications'),auto=$('#autoUpdates'),wifi=$('#wifiOnly'),preview=$('#previewMode');if(theme){theme.value=localStorage.getItem('nexus.theme')||'system';theme.addEventListener('change',()=>{localStorage.setItem('nexus.theme',theme.value);applyTheme()})}if(auto){auto.checked=localStorage.getItem('nexus.autoUpdates')!=='false';auto.addEventListener('change',()=>localStorage.setItem('nexus.autoUpdates',String(auto.checked)))}if(wifi){wifi.checked=localStorage.getItem('nexus.wifiOnly')==='true';wifi.addEventListener('change',()=>localStorage.setItem('nexus.wifiOnly',String(wifi.checked)))}if(preview){preview.value=localStorage.getItem('nexus.previewMode')||'wifi';preview.addEventListener('change',()=>localStorage.setItem('nexus.previewMode',preview.value))}if(notif){const supported='Notification'in window;notif.disabled=!supported;notif.checked=supported&&Notification.permission==='granted';notif.addEventListener('change',async()=>{if(notif.checked&&supported)notif.checked=(await Notification.requestPermission())==='granted'})}$('#installPwa')?.addEventListener('click',promptInstall)}
function renderAccount(){const unavailable=()=>alert('Compte Nexus bientôt disponible.');$('#nexusSignIn')?.addEventListener('click',unavailable);$('#nexusSignUp')?.addEventListener('click',unavailable)}
async function promptInstall(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}if(isIOS)alert('Safari → Partager → Ajouter à l’écran d’accueil');else alert('Installe Nexus Store depuis le menu du navigateur.')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-app-action]');if(!b)return;const a=apps.find(x=>x.id===b.dataset.appAction);if(a)install(a)});
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((localStorage.getItem('nexus.theme')||'system')==='system')applyTheme()});
async function load(){applyTheme();try{const r=await fetch('./catalog.json',{cache:'no-store'});apps=await r.json()}catch{apps=[]}({home:renderHome,search:renderSearch,categories:renderCategories,library:renderLibrary,app:renderDetail,settings:renderSettings,account:renderAccount}[page]||(()=>{}))()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});load();